<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class BarangDijual extends Model
{
    use HasFactory;
    protected $table='barang_dijual';
    protected $guarded=[];

    public function  scopeFilter($query, array $filters)
    {
        $query->when($filters['search'] ?? false, function($query, $search) {
            return $query->where('id_barang', 'like', '%' . $search . '%')
                ->orWhere('nama_barang', 'like', '%' . $search . '%');
        });

    }

    public function kategori()
    {
        return $this->belongsTo(Kategori::class, 'id_kategori', 'id_kategori');
    }

    public function transaksi ()
    {
        return $this->belongsTo(Transaksi::class);
    }

    public function detailPenjualan()
    {
        return $this->hasMany(DetailPenjualan::class,'id_barang', 'id_barang');
    }

    public function getRouteKeyName()
    {
        return 'id_barang'; // TODO: Change the autogenerated stub
    }
}
