<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function  scopeFilter($query, array $filters)
    {

//        if(request('search')){
//            return $query->where('id_barang', 'like', '%' . request('search') . '%');
//        }

        $query->when($filters['search'] ?? false, function($query, $search) {
//            $query->sortBy(['id_barang', 'asc']);
            return $query->where('id_barang', 'like', '%' . $search . '%')
                ->orWhere('nama_barang', 'like', '%' . $search . '%');
        });

//        $query->when($filters['search'] ?? false, function($query, $search) {
//            return $query->where('idBarang', 'like', '%' . $search . '%')
//                ->orWhere('body', 'like', '%' . $search . '%');
//        });
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getRouteKeyName()
    {
        return 'id_barang'; // TODO: Change the autogenerated stub
    }
}
